### PR TITLE
fix: update folder drop example

### PR DESCRIPTION
**Pull request by rolandjitsu**
**What kind of change does this PR introduce?**

- [x] bugfix
- [ ] feature
- [ ] refactoring / style
- [ ] build / chore
- [x] documentation

**Did you add tests for your changes?**

- [x] Yes, my code is well tested
- [ ] Not relevant

**If relevant, did you update the documentation?**

- [x] Yes, I've updated the documentation
- [ ] Not relevant

**Summary**

Fixed the folder drop example (used a different lib) and added some tests, and added more docs on plugins.

**Does this PR introduce a breaking change?**

No.

**Other information**

### CODE REVIEW

**Comment by rolandjitsu** [comment]
@okonet this should cover the plugin issue and folder support.

**Comment by rolandjitsu** [comment]
@okonet do you think we could get this PR and https://github.com/react-dropzone/react-dropzone/pull/673 (after I rebase it) merged?

**Comment by okonet** [comment]
@rolandjitsu I've added you as a collaborator so you're free to merge this PR.

**Comment by rolandjitsu** [comment]
@okonet to answer your questions:

1. In essence, it does achieve everything that the other lib did with some slight differences:
a. It's written in TS (makes it easier to maintain typings)
b. It returns native `File` objects patched with a `{path}` property
c. Provides es5 bundles (besides cjs, umd and es)
c. I chose to make a different lib because I thought it would be much faster to do so than make a PR with all the things + making releases
2. Do you mean replace the current default `getDataTransferItems()` with the one provided by the lib?
3. I am not against that, do you think it would be better to be in its own repo given that it's written in TS? And perhaps move it to this repo later on when/if this repo would also be written in TS (I think it would be a good idea and would help with maintaining typings)?

**Comment by rolandjitsu** [comment]
@okonet thanks a bunch, I appreciate that.

**Comment by okonet** [comment]
I’m open to TS in this repo if you’re up for it BTW.

**Comment by okonet** [comment]
And to 3. I think it’s own repo is fine as long it is in this org

**Comment by rolandjitsu** [comment]
Ok, I will move the lib to this org and make sure the auto publish from Travis still works. I'm open to work on migrating to TS, but later on when I have more time on my hands.

**Pull request merged**
