### PR TITLE
Create CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by DeFuex**
**What kind of change does this PR introduce?**

- [ ] bugfix
- [ ] feature
- [ ] refactoring / style
- [ ] build / chore
- [x] documentation

**Did you add tests for your changes?**

- [ ] Yes, my code is well tested
- [x] Not relevant

**If relevant, did you update the documentation?**

- [ ] Yes, I've updated the documentation
- [x] Not relevant

**Summary**

Creating a contributing.md file to maintain order in this repository and between every contributor that likes to work on this open source project.

**Other Information**
sry for the inconvenience. i forgot to branch off the master branch when doing a PR for #511 ...that is why this pr includes these first commits.

### CODE REVIEW

**Comment by SaraVieira** [comment]
Thanks for the PR!

Can you walk me through what the other changes are?

**Comment by DeFuex** [comment]
Hi @SaraVieira ...i accidentally forgot to make a different branch for pr #511 and therefore i have everything from my master branch (which is on a different PR) in this PR. Hopefully shouldn't be a problem though.

**Comment by SaraVieira** [comment]
Hello @DeFuex,

When that one gets approved we will merge this then :)

**Comment by okonet** [comment]
@DeFuex could you please resubmit this one from a branch? Thanks!

**Pull request closed without merging**
