### PR TITLE
build: fix node 20 build and update imagemin version

### PR DESCRIPTION
**Pull request by rolandjitsu**
**What kind of change does this PR introduce?**
- [ ] Bug Fix
- [ ] Feature
- [ ] Refactoring
- [ ] Style
- [x] Build
- [ ] Chore
- [ ] Documentation
- [ ] CI

**Did you add tests for your changes?**
- [x] Yes, my code is well tested
- [ ] Not relevant

**If relevant, did you update the documentation?**
- [x] Yes, I've updated the documentation
- [ ] Not relevant

**Summary**

On node 20+, `yarn install` doesn't work anymore due to the `node-sass` dep. There's also a step to be taken on Apple silicon for imagemin to build.

**Does this PR introduce a breaking change?**

No.

**Other information**

### CODE REVIEW

**Comment by JandenMa** [comment]
image

the package requires Node > 20.17 without any breaking change notification

**Comment by rolandjitsu** [comment]
Well, the intent was to fix the builds failing. There was no change to the source that should require a major change (nothing that affects how it functions in the browser).

It's unfortunate that the nodejs ecosystem doesn't provide the means to differentiate b/t needing a node version for dev/build purposes vs runtime dependency (maybe it does and I'm not aware of it).

In any case, this obviously needs fixing and I apologise for the inconvenience. I'll see if there is a way to fix it without having to release a major version.

**Comment by JandenMa** [comment]
> Well, the intent was to fix the builds failing. There was no change to the source that should require a major change (nothing that affects how it functions in the browser).
> 
> It's unfortunate that the nodejs ecosystem doesn't provide the means to differentiate b/t needing a node version for dev/build purposes vs runtime dependency (maybe it does and I'm not aware of it).
> 
> In any case, this obviously needs fixing and I apologise for the inconvenience. I'll see if there is a way to fix it without having to release a major version.

No rush I locked the version in 14.2.3 for now.

**Comment by trungdq88** [comment]
>  I'll see if there is a way to fix it without having to release a major version.

I don't think there's a way to do it without increasing the major version. It's how semver is agreed on.

I'm locking on 14.2.3 for now too.

**Comment by rolandjitsu** [comment]
https://github.com/react-dropzone/react-dropzone/pull/1373 should fix the issue with the min required version.

**Pull request merged**
