### PR TITLE
Feature validate file by array schema with specific type (Need discussion more)

### PR DESCRIPTION
**Pull request by hieusmiths**
**What kind of change does this PR introduce?**

- [ ] bugfix
- [x] feature
- [ ] refactoring / style
- [ ] build / chore
- [ ] documentation

**Did you add tests for your changes?**
I need help
- [ ] Yes, my code is well tested
- [ ] Not relevant

**If relevant, did you update the documentation?**
I will update later
- [ ] Yes, I've updated the documentation
- [ ] Not relevant

**Summary**

For example, we should built-in a validator with specific file type:

Suppose we have multiple input and the requirement is { type: pdf, maxSize: 50 } { type: video, maxSize: 100 } and some like name file, ...

So we can pass into hook look like:

const {} = useDropX({  
 validatorSchema: [
  { type: pdf, maxSize: 50, validator: optional function } { type: video, maxSize: 100 }
 ]
 })

**Does this PR introduce a breaking change?**

**Other information**

I have a problem when format the code. Can you help me re-format them after PR is stable?

### CODE REVIEW

**Review by rolandjitsu — CHANGES_REQUESTED** [review]
Please undo all the format changes so we can understand the changes you've made.

**Comment by hieusmiths** [comment]
> Please undo all the format changes so we can understand the changes you've made.

Okay let me do

**Comment by rolandjitsu** [comment]
@hieusmiths are you still interested in continuing work on this PR? Otherwise I'll close it.

**Comment by rolandjitsu** [comment]
Closing this.

**Pull request closed without merging**
