### PR TITLE
chore: upgrade attr-accept

### PR DESCRIPTION
**Pull request by rkmarks**
**What kind of change does this PR introduce?**

- [ ] bugfix
- [ ] feature
- [ ] refactoring / style
- [x] build / chore
- [ ] documentation

**Did you add tests for your changes?**

- [ ] Yes, my code is well tested
- [x] Not relevant

**If relevant, did you update the documentation?**

- [ ] Yes, I've updated the documentation
- [x] Not relevant

**Summary**
Upgraded attr-accept to avoid babel issues and solves for #566

### CODE REVIEW

**Comment by Nodman** [comment]
I did builds, both with `1.0.3` and `1.1.3`, `npm size` shows same values:

`5.57 KB for dist/index.js`
`3072 B for dist/es/index.js`

🤔

**Comment by rkmarks** [comment]
Yeah same here, did it just yesterday. Which makes me wonder if something else node_module wise increased in size recently?

**Comment by okonet** [comment]
Not sure how this is possible that the build has been working still if one of the deps increased? I don't want to block the PR, though. Please feel free to decide on your own if it's worth merging without addressing this.

**Comment by okonet** [comment]
@rkmarks can you tell why it was wrong initially?

**Comment by rkmarks** [comment]
@okonet i could not tell why the sizes were different. actually for me even when i installed a previous version the size was the same as my change. not sure 🤷‍♂️

**Pull request merged**
