### PR TITLE
Fix: Dragging multiple files when multiple false doesn't apply rejectStyle

### LINKED ISSUE #488: Dragging multiple files when multiple false doesn't apply rejectStyle
- [x] I found a bug
- [ ] I want to propose a feature

When the rejectStyle and acceptStyle props are used, the reject style does not get applied in the case when multiple is set to false and multiple files that are allowed are dragged over the drop-zone

1. Create Dropzone with the following props:
```
   <Dropzone
     accept="jpg"
     multiple={false}
    rejectStyle={{
      color: 'red',
       borderColor: 'red',
    }}
    acceptStyle={{
      color: 'green',
      borderColor: 'green',
    }}
   >
    <p>Content</p>
  </Dropzone>
```
2. Drag a jpg file over - get green border and text
3. Drag a .zip file over - get red border and text
4. Drag 2x .jpg files over - get green border and text.

**What is the expected behavior?**
Expect 'rejected' style (red border and text) to be applied when multiple=false and drag more than 1 file

Issue is here: https://github.com/react-dropzone/react-dropzone/blob/b8c99df996f27fc76a8cbf652e16ad50489592b4/src/index.js#L345

I have created a fork that will apply both accept and reject styles (with reject being applied after)

### PR DESCRIPTION
**Pull request by ianhowe76**
**What kind of change does this PR introduce?**

- [x] bugfix
- [ ] feature
- [ ] refactoring / style
- [ ] build / chore
- [ ] documentation

**Did you add tests for your changes?**

- [x] Yes, my code is well tested
- [ ] Not relevant

**If relevant, did you update the documentation?**

- [ ] Yes, I've updated the documentation
- [x] Not relevant

**Summary**

**Does this PR introduce a breaking change?**

**Other information**
closes #488

### CODE REVIEW

**Comment by okonet** [comment]
Thanks for submitting it! Could you please add a relevant test for it?

**Comment by ianhowe76** [comment]
Added tests

**Comment by okonet** [comment]
@ianhowe76 CI build is failing. Can you please fix it?

**Comment by okonet** [comment]
Thanks @ianhowe76 for working on this!

**Pull request merged**
