### PR TITLE
fix: `isDragReject` now true if a file is not within size range

### LINKED ISSUE #861: 'isDragReject' not called when excceeded maxSize
**Do you want to request a *feature* or report a *bug*?**

- [X] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

1. Listen for `isDragReject` event and set `maxSize` parameter
2. Drag file in front of drop zone
3. Event `isDragReject` not fire when file is larger than `maxSize` parameter

### PR DESCRIPTION
**Pull request by TheLordHighExecutioner**
**What kind of change does this PR introduce?**

- [x] bugfix
- [ ] feature
- [ ] refactoring / style
- [ ] build / chore
- [ ] documentation

**Did you add tests for your changes?**

- [x] Yes, my code is well tested
- [ ] Not relevant

**If relevant, did you update the documentation?**

- [ ] Yes, I've updated the documentation
- [x] Not relevant

**Summary**

Previously, `isDragReject` would not trigger if a file was not within the specified size range. For example, it would not return `true` if a file was too large. See: https://github.com/react-dropzone/react-dropzone/issues/861. This is because it was not checking for size.

**Does this PR introduce a breaking change?**

No

**Other information**

Fixes #861

### CODE REVIEW

**Comment by TheLordHighExecutioner** [comment]
Suggestion: `onDropAccepted` and `isDragAccepted` should probably behave similarly. A file should trigger both or neither, but not only one.

They both rely on the expression `fileAccepted(file, accept) && fileMatchSize(file, maxSize, minSize)`. Thus, I suggest extracting this to its own function (I could include that in this PR).

**Comment by rolandjitsu** [comment]
Please rebase your PR. I will check it soon to verify that this change doesn't break some intended behavior.

**Comment by TheLordHighExecutioner** [comment]
> Please rebase your PR. I will check it soon to verify that this change doesn't break some intended behavior.

Just rebased it!

**Pull request merged**
