### PR TITLE
refactor: deprecate {disableClick}

### PR DESCRIPTION
**Pull request by rolandjitsu**
**What kind of change does this PR introduce?**

- [ ] bugfix
- [ ] feature
- [x] refactoring / style
- [ ] build / chore
- [ ] documentation

**Did you add tests for your changes?**

- [ ] Yes, my code is well tested
- [x] Not relevant

**If relevant, did you update the documentation?**

- [x] Yes, I've updated the documentation
- [ ] Not relevant

**Summary**

We're deprecating the `{disableClick}` property as the same result can be achieved using idiomatic js/react.

**Does this PR introduce a breaking change?**

No.

**Other information**

### CODE REVIEW

**Comment by rolandjitsu** [comment]
@okonet it seems that `refactor` commits do not get released. What should we do about this?

**Comment by okonet** [comment]
Yeah it should have been a feature one. You could force a release with an empty commit I think. Not sure tbh

**Comment by rolandjitsu** [comment]
@okonet I guess we'll release this with the next bug fix. I'm working on figuring out what to do about #755 as it seems Safari is reporting the drag item type as file, so there will be a PR soon.

**Comment by goodoldneon** [comment]
The default prop for `disableClick` is `false`, which means the deprecation warning appears unless `disableClick` is explicitly set it to `null`. I'd think a deprecation warning shouldn't appear if the deprecated prop isn't specified. Is this behavior expected?

**Comment by rolandjitsu** [comment]
@goodoldneon You're right, it should not appear unless the user uses it. But this prop will be removed and it should not be the case anymore.

**Pull request merged**
