### PR TITLE
Chrome 63 hangs dragging a file onto the drop zone whilst the file dialog is open.

### PR DESCRIPTION
**Pull request by dennisroche**
**What kind of change does this PR introduce?**

- [x] bugfix
- [ ] feature
- [ ] refactoring / style
- [ ] build / chore
- [ ] documentation

**Did you add tests for your changes?**

- [ ] Yes, my code is well tested
- [x] Not relevant

**If relevant, did you update the documentation?**

- [ ] Yes, I've updated the documentation
- [x] Not relevant

**Summary**

Chrome 63 hangs dragging a file onto the drop zone whilst the file dialog is open. 

https://github.com/react-dropzone/react-dropzone/issues/549

### CODE REVIEW

**Comment by dennisroche** [comment]
Also included is a fix to allow the project to be built/tested on Windows using `cross-env`.

**Comment by rkmarks** [comment]
LGTM

**Comment by dennisroche** [comment]
comment added. 

```js
    try {
      // The file dialog on Chrome allows users to drag files from the dialog onto
      // the dropzone, causing the browser the crash when the file dialog is closed.
      // A drop effect of 'none' prevents the file from being dropped
      evt.dataTransfer.dropEffect = this.isFileDialogActive ? 'none' : 'copy' // eslint-disable-line no-param-reassign
    } catch (err) {
      // continue regardless of error
    }
```

**Comment by okonet** [comment]
Could you probably split the cross-env and fix into 2 PRs? I’m usually squash merge and prefer commits to be related to the stuff they implement.

**Comment by okonet** [comment]
Or, alternatively, please squash the comment into the previous fix commit and I’ll rebase merge

**Comment by okonet** [comment]
If you prefer rebasing, please add a reference to the bug in the commit message.

**Comment by dennisroche** [comment]
sure. splitting the pr and i'll do the rebase with bug ref. 

we should create a `CONTRIBUTING.md`

**Comment by dennisroche** [comment]
rebased as requested. split xplat changes to https://github.com/react-dropzone/react-dropzone/pull/553

**Comment by okonet** [comment]
@dennisroche thank you for doing this. I'd love if you could work on `Contributing.md`!

**Comment by dennisroche** [comment]
@okonet I'll kick off a `Contributing.md` PR

**Pull request merged**
