### PR TITLE
Delete vendor directory

### PR DESCRIPTION
**Pull request by rikschennink**
See: https://github.com/react-dropzone/react-dropzone/issues/1076

**What kind of change does this PR introduce?**

- [ ] bugfix
- [ ] feature
- [ ] refactoring / style
- [ ] build / chore
- [x] documentation

**Did you add tests for your changes?**

- [ ] Yes, my code is well tested
- [x] Not relevant

**If relevant, did you update the documentation?**

- [ ] Yes, I've updated the documentation
- [x] Not relevant

**Summary**

See: https://github.com/react-dropzone/react-dropzone/issues/1076

**Does this PR introduce a breaking change?**

Probably documentation example will stop working.

Can link to here as an alternative: https://codesandbox.io/s/react-dropzone-pintura-40xh4?file=/src/App.js

### CODE REVIEW

**Comment by s100** [comment]
I believe this PR is failing CI because the `doka` code is actually used at development time to ensure that the example still works? I have opened #1084 which leaves the `vendor` directory in the repo but ensures that it will no longer be distributed as part of `react-dropzone`.

I'll leave it to the maintainers to decide which PR they're in favour of. We are also having trouble with #1076 and for our purposes either PR would fix the issue.

**Comment by rolandjitsu** [comment]
@rikschennink I think this should be fixed by https://github.com/react-dropzone/react-dropzone/pull/1086 now. So we can keep the pintura assets if that's ok. Otherwise, we also need to remove the example doc.

**Comment by rikschennink** [comment]
@rolandjitsu While I'm fine with that, I think it would be best to remove the files altogether so there's 0 chance for confusion.

**Comment by rolandjitsu** [comment]
@rikschennink sure thing. Then we need to remove:
1. The [example](https://github.com/react-dropzone/react-dropzone/tree/master/examples/doka)
2. https://github.com/react-dropzone/react-dropzone/blob/623623e8a8363d06e098aee5eeade3927e8def55/styleguide.config.js#L22
3. https://github.com/react-dropzone/react-dropzone/blob/623623e8a8363d06e098aee5eeade3927e8def55/styleguide.config.js#L26
4. https://github.com/react-dropzone/react-dropzone/blob/623623e8a8363d06e098aee5eeade3927e8def55/styleguide.config.js#L84

And we should be good to go after that.

**Comment by rolandjitsu** [comment]
@rikschennink did you manage to 

> @rikschennink sure thing. Then we need to remove:
> 
> 1. The [example](https://github.com/react-dropzone/react-dropzone/tree/master/examples/doka)
> 2. https://github.com/react-dropzone/react-dropzone/blob/623623e8a8363d06e098aee5eeade3927e8def55/styleguide.config.js#L22
> 3. https://github.com/react-dropzone/react-dropzone/blob/623623e8a8363d06e098aee5eeade3927e8def55/styleguide.config.js#L26
> 4. https://github.com/react-dropzone/react-dropzone/blob/623623e8a8363d06e098aee5eeade3927e8def55/styleguide.config.js#L84
> 
> And we should be good to go after that.

@rikschennink do you think you could do the above to get this PR merged?

**Comment by rikschennink** [comment]
@rolandjitsu totally forgot about this, just made the required changes. 

Instead of removing I've renamed the Doka documentation page to Pintura and removed the live example.

**Comment by rolandjitsu** [comment]
> @rolandjitsu totally forgot about this, just made the required changes.
> 
> Instead of removing I've renamed the Doka documentation page to Pintura and removed the live example.

The deployment is failing:
```
8:52:34 AM: ./examples/pintura/README.md (./node_modules/react-styleguidist/lib/loaders/examples-loader.js!./examples/pintura/README.md)
8:52:34 AM: Module not found: Can't resolve 'pintura' in '/opt/build/repo/examples/pintura'
./examples/pintura/README.md (./node_modules/react-styleguidist/lib/loaders/examples-loader.js!./examples/pintura/README.md)
8:52:34 AM: Module not found: Can't resolve 'pintura/pintura.css' in '/opt/build/repo/examples/pintura'
```

It's probably because you need to mark the example as static (`jsx static`).

**Comment by rikschennink** [comment]
@rolandjitsu okay, changed

**Review by rolandjitsu — APPROVED** [review]

**Pull request merged**
