### PR TITLE
fix: fix file filter PR regression

### PR DESCRIPTION
**Pull request by rolandjitsu**
**What kind of change does this PR introduce?**

- [x] bugfix
- [ ] feature
- [ ] refactoring / style
- [ ] build / chore
- [ ] documentation

**Did you add tests for your changes?**

- [x] Yes, my code is well tested
- [ ] Not relevant

**If relevant, did you update the documentation?**

- [ ] Yes, I've updated the documentation
- [x] Not relevant

**Summary**

Provide fix for https://github.com/react-dropzone/react-dropzone/pull/619#issuecomment-426573278.

**Does this PR introduce a breaking change?**

No.

**Other information**
It also fixes some of the errors from the docs page.

### CODE REVIEW

**Comment by rolandjitsu** [comment]
@okonet note that the folder drop example is not going to work because the plugin that it's used to illustrate this case does not return a list of native `File` objects.

The only viable option I see here is to extend the native `File` object and add the additional props, but this is something that the plugin author would need to do.

Alternatively, I could make another plugin which would do just that.

**Comment by okonet** [comment]
That’s bummer. Does this mean the plugin we’re using becomes incompatible with this fix? What would the fix for it look like?

**Comment by rolandjitsu** [comment]
Pretty much. We could add a specific check for the object type the plugin returns (see [Html5FileSelector.js#L71](https://github.com/quarklemotion/html5-file-selector/blob/master/src/Html5FileSelector.js#L71)), but I think that would be a mistake.

I think that plugins should comply with the type signature that this component requires for `getDataTransferItems()` (as illustrated in [#673](https://github.com/react-dropzone/react-dropzone/pull/673/files#diff-7359d6ad5f8dd67c439f94fc95f12d5eR57)). 

In any case, allowing plugins to return any kind of objects might cause some confusion for users as they would probably expect the callbacks (`onDrop()`, etc.) to be called with `File` (`FileWithPreview`) objects which they then can upload to a server (as an example).

So I guess we could either:

- make plugins comply with the same type signature for `getDataTransferItems()` and I could make another plugin which would do that (or make a PR for the current one)
- or expose `isFileList()` as a property (under some other name) which the plugin would also have to provide.

**Comment by okonet** [comment]
I agree with the argument that users expect `File`s to be returned. Let's do the following:

1. Merge and release this PR
1. Make a PR for the current plugin for folders
1. Update the documentation for the function signature to make it clear
1. Add a test (not sure this is not covered yet)

**Pull request merged**
